
# We will create the composite action to use in our workflow

name: random joke
author: omkar
description: this jobe will create a random joke

inputs:
  salck_username:
    description: 'Slack username'
    required: true
  upload_joke:
    description: 'Upload the joke as artifact ?'
  slack_webhook_url:
    description: 'Slack webhook URL'
outputs:
  joke:
    description: 'The random joke created by the action'
    value: ${{ steps.joke.outputs.random_joke }}
    
runs:
  using: 'composite'
  steps:
    - name: Create a random joke
      shell: bash 
      id: joke
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "random_joke<<$EOF" >> "$GITHUB_OUTPUT"
        curl -s https://icanhazdadjoke.com/ >> "$GITHUB_OUTPUT"
        echo "" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
    - name: Upload the joke as artifact
      shell: bash
      run: |
        echo "${{ steps.joke.outputs.random_joke }}" > random-joke.txt
      if: ${{ inputs.upload_joke == 'true' }}
    - uses: actions/upload-artifact@v4
      with:
        name: random-joke-name
        path: random-joke.txt
    - name: Post the joke to Slack
      uses: docker://technosophos/slack-notify
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_TITLE: Random Joke
        SLACK_MESSAGE: "${{ inputs.salck_username && format('{0}{1} {2}', '@', inputs.salck_username, steps.joke.outputs.random_joke) || steps.joke.outputs.random_joke }}"
        SLACK_COLOR: "#723fc4"
