name: "code for parallel and dependent jobs"
on: [push]

jobs:
  run_shell_cmd_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hello world"
      - run: doesnotexist
  run_parallel_job:
    runs-on: windows-latest
    steps:
      - name: echo window
        run: Write-Output "from windows"
  run-depended-job:
    runs-on: ubuntu-latest
    needs: run_shell_cmd_job
    steps:
      - name: make dir
        run: | 
          mkdir new
          touch new.txt
          ls -ltr
    
