name: new wf for checking the events
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  issues:
    types: [opened]
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for events 01 child workflow edited again
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_EVENT_NAME
