name: new wf for checking the events
on:
  push:
    branches:
      - main
      - chilld-branch
  pull_request:
    branches:
      - chilld-branch
      - main
  workflow_dispatch:
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for events
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_EVENT_NAME
