name: workflow event
on:
  workflow_run:
    workflows: [new wf for checking the events]
    types: [completed]
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Check event edited
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow name: ${{ github.event.workflow }}"
