name: checkout brnach
on: [push]
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: check 01
        run: |
          ls -al
      - name: checkout step
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository.omomomomomom }}/{demo-repo-by-terraform-01}
      - name: check 02
        run: |
          ls -al
