name: checkout brnach
on: [push]
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: check 01
        run: |
          ls -al
      - name: checkout step
        run: actions/checkout@v2
      - name: check 02
        run: |
          ls -al
