name: secretes and variables

on: [push]
jobs:
    job_01:
        runs-on: ubuntu-latest
        environment: production
        env:
            env_var: ${{vars.ENV_VAR}}
            repo_var: ${{ vars.REPO_VAR }}
            repo_secret: ${{ secrets.REPO_SECRET }}
            prod_secret: ${{ secrets.PROD_SECRETE }}
            staging_secret: ${{ secrets.STAG_SECRET }}
        steps:
            - name: step 01
              run: |
                    echo "This is a env variable: $env_var"
                    echo "This is a repo variable: $repo_var"
                    echo "This is a repo secret: $repo_secret"
                    echo "This is a production secret: $prod_secret"
                    echo "This is a staging secret: $staging_secret"
