name: using docker-slack-notify
# Description: A GitHub Actions workflow that runs a script in a Docker container and sends a notification to Slack.
on: [workflow_dispatch]

jobs:
    job_01:
        runs-on: ubuntu-latest
        container: 
            image: node:24-alpine3.21
            env:
                CONTAINER_ENV_VAR: "JOB_ENV_VAR_he_bhai"
            ports: 
                - 3000
        steps:
           - uses: actions/checkout@v3
           - name: run in docker
             uses: docker://node:24-alpine3.21
             with:
                entrypoint: /bin/sh
                args: |
                    -c "chmod +x script.sh && \
                    ./script.sh 'hello world of GHA' && \
                    mount | grep '/github/workspace'"
           - name: using slack-notify
             uses: docker://technosophos/slack-notify
             env:
                SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
                SLACK_USERNAME: "BrigadeBot"
                SLACK_TITLE: "title goes here"
                SLACK_MESSAGE: "Actor: ${{ github.actor }} and event: ${{ github.event_name }}"
                SLACK_COLOR: "#ff69b4"
