name: using docker
on: [workflow_dispatch]

jobs:
    job_01:
        runs-on: ubuntu-latest
        container: 
            image: node:24-alpine3.21
            env:
                CONTAINER_ENV_VAR: "Container Level Environment Variable"
            ports: 
                - 3000
            volumes:
                - /tmp:/tmp
            #options: --entrypoint /bin/sh 

        steps:
            - run: |
                node --version
                cat /etc/os-release
            - name: log env var
              run: echo "$CONTAINER_ENV_VAR"
            - name: run under diff docker
              uses: docker://node:22-alpine3.21
              with:
                args: -v
            - uses: docker://node:24-bookworm-slim
              with:
                args: -p 3+4 /etc/os-release
                   
                    
                

            
