name: output sample 
on: [push]
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: step 01
        run: echo "key01=value 01" >> $GITHUB_OUTPUT
        id: step_01
      - run: echo "key02=value 02" >> $GITHUB_OUTPUT
        id: step_02
      - name: step 02
        run: |
          echo ${{steps.step_02.outputs.key02}} >> $GITHUB_OUTPUT
          echo ${{steps.step_01.outputs.key01}} >> $GITHUB_OUTPUT
