name: output sample 
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest,windows-latest'
      node-v:
        description: 'Node.js version'
        required: true
        default: '16,18'
jobs:
  job_01:
    runs-on: ubuntu-latest
    outputs:
      matrix-array: ${{ steps.convert_to_array.outputs.result }}
    steps:
      - name: convert to array
        uses: actions/github-script@v6
        id: convert_to_array
        with:
          script: "return {os: context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-v'].split(',')}"
          result-encoding: json
      - name: step 01
        id: step_01
        run: echo "key01=value 01" >> $GITHUB_OUTPUT
      - name: step 02
        id: step_02
        run: echo "key02=value 02" >> $GITHUB_OUTPUT
      - name: print outputs
        run: |
          echo "${{ steps.step_01.outputs.key01 }}"
          echo "${{ steps.step_02.outputs.key02 }}"
  job_02:
    continue-on-error: ${{ matrix.node-version==19}}
    needs: job_01
    strategy:
      matrix:
        os: ${{fromJson(needs.job_01.outputs.matrix-array).os}}
        node-version: ${{fromJson(needs.job_01.outputs.matrix-array).node-version}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: step 01
        run: |
          echo ${{ matrix.os }} and ${{ matrix.node-version }}
      - name: step 02
        if: ${{matrix.os=='windows-latest'}}
        run: exit 1
