name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: error
      - run: echo "This will not run because the previous step failed."
  test2:
    #continue-on-error: true
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - run: echo "This will run only if the previous job succeeded."
      - run: echo "This will not run because the previous step failed."
