name: check the status of the steps
on: [push]
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: exit 1
        id: step_1
      - name: Step 1.1
        run: echo "this will run"
      - name: Step 2
        if: failure()
        run: echo "This step will run if the previous step fails"
      - name: Step 3
        run: echo "this will n\ot run as 3rd step"
      - name: Step 4
        if: failure() && steps.step_1.outcome == 'failure'
        run: echo "This step will run if only step 1.1 fails"
      - name: Step 5
        if: always()
        run: echo "This is step 5"
