name: matrix with time
on: [push]
jobs:
  matrix-job:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: node -v


