name: sample-workflow
on: [push]
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "This is a sample workflow step"
      - run: exit 1
      - run: echo "step after exit 1"
  job02:
    runs-on: ubuntu-latest
    needs: job01
    steps:
      - name: Run a script
        run: echo "This is another sample workflow step"
  job03:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "This is yet another sample workflow step"
