name: reusable from same repo
on:
  workflow_call:
    outputs:
      date:
        value: ${{jobs.job_01_same_repo.outputs.date}}
jobs:
  job_01_same_repo:
    runs-on: ubuntu-latest
    outputs:
      date: ${{steps.date-op.outputs.date}}
    steps:
      - run: echo "date=$(date)" >> $GITHUB_OUTPUT
        id: date-op
    
