name: guthub workflow for the shell
on: [push]
jobs:
  job_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: step 01
        run: |
          pwd
          echo "sample text" > file01.txt
          ls -a
          cat file01.txt
          echo $GITHUB_SHA
      
  job_on_windows:
    runs-on: ubuntu-latest
    steps:
      - name: step 01
        shell: pwsh
        run: |
          pwd
          Get-Location
          dir
          echo $env:GITHUB_SHA
      - name: python script
        shell: python
        run: |
          print("hello world")
    
  
    
