name: workflow for opt consoles
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step 01
        run: echo "::error title=error he::error he 1"
      - name: step 02
        run:  echo "::debug title=debug he::debug he 2"
      - name: step 03
        run:  echo "::notice titl=:notice he::notice he 3"
      - name: step 04
        run: echo "::warning title=warning he::warning he 4"
      - name: add-mask
        run: "echo ::add-mask::Pa55w0rd"
      - run: "echo Pa55w0rd"
      - run: echo "::warning::warring 02 he"
      
