name: workflow for opt consoles
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step 01
        run: "echo ::error title: error he:: error he"
      - name: step 02
        run:  "echo ::debug title: debug he:: debug he"
      - name: step 03
        run:  "echo ::notice title: notice he:: notice he"
      - name: step 04
        run: "echo ::warning title: warning he:: warning he"
