name: workflow dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the workflow'
        required: true
        default: 'workflow_dispatch'
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "${{ inputs.environment }} and ${{ inputs.name }}"
