name: guthub workflow for the shell
on: [push]
jobs:
  job_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: step 01
        run: |
          pwd
          touch echo"sample text" > file01.txt
          ls -a
          cat file01.txt
          echo $GITHUB_SHA
      
  job_on_windows:
    runs-on: windows-latest
    steps:
      - name: step 01
        run: |
          pwd
          Get-Location
          dir
          echo $GITHUB_SHA
    
  
    
